wechat:
  client:
    clientId: wxfb72a080bd030afc
    clientSecret: 904b37a6a9fda7b7da951425a8644e3b
    accessTokenUri: https://api.weixin.qq.com/sns/oauth2/access_token
    userAuthorizationUri: https://open.weixin.qq.com/connect/qrconnect
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.weixin.qq.com/sns/userinfo